-- Add onboarding habit, biometric, and RPG stats columns to public.profiles
alter table public.profiles 
  add column if not exists gender text,
  add column if not exists age integer,
  add column if not exists weight numeric(5,2),
  add column if not exists height numeric(5,2),
  add column if not exists body_fat numeric(5,2),
  add column if not exists muscle_percent numeric(5,2),
  add column if not exists social_hours numeric(5,2),
  add column if not exists book_pages integer,
  add column if not exists book_title text,
  add column if not exists train_days integer,
  add column if not exists focus_exercises text[] default '{}'::text[],
  add column if not exists calories_target integer,
  add column if not exists protein_target integer,
  add column if not exists cardio_option boolean default false,
  add column if not exists cardio_sport text,
  add column if not exists cardio_calories integer,
  add column if not exists wake_time text,
  add column if not exists sleep_quality text,
  add column if not exists water_target numeric(5,2),
  add column if not exists water_reminder boolean default false,
  add column if not exists wisdom integer default 40,
  add column if not exists confidence integer default 40,
  add column if not exists strength integer default 40,
  add column if not exists discipline integer default 40,
  add column if not exists focus integer default 40;
